# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

height = 4000000

a_count = 1
b_count = 2 
count = 0
def menora_height():
	return a_count >= height or b_count >= height


while True:


	if a_count % 2 == 0: count += a_count
	if menora_height(): break
	a_count += b_count
	
	if b_count % 2 == 0: count += b_count
	if menora_height(): break
	b_count += a_count

	print( 'a[{}] ______ b[{}]_________ last[{}]'. format( a_count, b_count, count) )

print('result: ', count)